<?php
/**
 * MsProAdmin is forked from Min-eAdmin, with the aim of building the system more customizable and faster
 */

declare(strict_types=1);
namespace MsPro\Command;

use Hyperf\Command\Annotation\Command;
use MsPro\MsProCommand;

/**
 * Class MsProAdmin
 * @package System\Command
 */
#[Command]
class MsProAdmin extends MsProCommand
{
    protected ?string $name = 'mspro';

    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * Handle the current command.
     */
    public function handle()
    {
        $result = shell_exec('php ' . BASE_PATH . '/bin/hyperf.php | grep mspro');
        $this->line($this->getInfo(), 'comment');
        $this->line(preg_replace('/\s+mspro\s+/', '', $result), 'info');
    }
}